.PHONY: clean All

All:
	@echo "----------Building project:[ Tarea1Ejercicio3 - Debug ]----------"
	@cd "Tarea1Ejercicio3" && $(MAKE) -f  "Tarea1Ejercicio3.mk"
clean:
	@echo "----------Cleaning project:[ Tarea1Ejercicio3 - Debug ]----------"
	@cd "Tarea1Ejercicio3" && $(MAKE) -f  "Tarea1Ejercicio3.mk" clean
