.PHONY: clean All

All:
	@echo "----------Building project:[ Tarea1Ejercicio1 - Debug ]----------"
	@cd "Tarea1Ejercicio1" && $(MAKE) -f  "Tarea1Ejercicio1.mk"
clean:
	@echo "----------Cleaning project:[ Tarea1Ejercicio1 - Debug ]----------"
	@cd "Tarea1Ejercicio1" && $(MAKE) -f  "Tarea1Ejercicio1.mk" clean
